# Site settings
title: 饮冰十年，热血难凉。
email: vincentzengcn@outlook.com
description: "一个博客。"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://longlongzone.com" # the base hostname & protocol for your site
github_username:  shangrilalala
#Not now disqus: shangrilalala
paginate: 10000
paginate_path: "blog/page:num/"
# Build settings
markdown: kramdown
permalink: /:year-:month-:day/:title.html
gems: [jekyll-paginate]